version: 2
jobs:
  build-test:
    docker:
      - image: circleci/node:10.9.0
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-test-dependencies-{{ checksum "yarn.lock" }}
            - v1-test-dependencies-
      - run:
          name: Install Project Dependencies
          command: |
            yarn install --frozen-lockfile
      - run:
          name: Run the Test
          command: |
            yarn test
      - save_cache:
          paths:
            - node_modules
          key: v1-test-dependencies-{{ checksum "yarn.lock" }}
  reversion:
    docker:
      - image: cibuilds/github:0.12
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-revision-dependencies-{{ checksum "yarn.lock" }}
            - v1-revision-dependencies-
      - run:
          name: "Echo a Thing"
          command: |
            echo "A Thing"
      - run:
           name: "Get the version from package.json"
           command: | 
             ./scripts/extract-version.sh
      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION=$(./scripts/extract-version.sh)
            ghr -t ${GHTOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./src/
      - save_cache:
          paths:
            - node_modules
          key: v1-revision-dependencies-{{ checksum "yarn.lock" }}


workflows:
  version: 2
  build-test-version:
    jobs:
      - build-test
      - reversion:
          requires:
            - build-test
